// SPDX-License-Identifier: Apache-2.0
#include "cuda_compute.h"

#include <algorithm>
#include <cstring>
#include <cxxabi.h>
#include <mutex>
#include <sstream>

#include <cuda_runtime_api.h>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

#include "cl_kernels.h"
#include "cuda_kernel_table.h" // generated by CMake: {kernel_<name>_cl, "<name>"} for every kernel/*.cl


#define CUDA_CHECK(call) do { \
	cudaError_t cudaCheckError = (call); \
	if(cudaCheckError != cudaSuccess) { \
		FATAL("[CUDA] " << #call << " failed: " << cudaGetErrorName(cudaCheckError) << " (" << cudaGetErrorString(cudaCheckError) << ")"); \
	} \
} while(false)


const PixelFormat PixelFormat::RGBA8 = PixelFormat(4, 1, true, CV_8UC4, 4);
const PixelFormat PixelFormat::U8 = PixelFormat(1, 1, false, CV_8UC1, 1);
const PixelFormat PixelFormat::F32 = PixelFormat(4, 1, false, CV_32FC1, 4);
const PixelFormat PixelFormat::NV12 = PixelFormat(1, 2, true, CV_8UC1, 0); //Do not use as image format or with OpenCV, intended for usage with RTPStreamer (TODO overallocated, actual necessary size is just 3/2)

const PixelFormat PixelFormat::RGGB8 = PixelFormat(2, 2, true, CV_8UC1, 0, "-DRGGB");
const PixelFormat PixelFormat::GRBG8 = PixelFormat(2, 2, true, CV_8UC1, 0, "-DGRBG");
const PixelFormat PixelFormat::BGR8 = PixelFormat(3, 1, true, CV_8UC3, 0, "-DBGR"); //Do not use as image format


namespace vpcuda {

struct EventPair {
	EventPair() {
		CUDA_CHECK(cudaEventCreate(&start));
		CUDA_CHECK(cudaEventCreate(&end));
	}
	~EventPair() {
		// Ignore errors, the CUDA context might already be torn down at process exit
		cudaEventDestroy(start);
		cudaEventDestroy(end);
	}
	EventPair(const EventPair&) = delete;
	EventPair& operator=(const EventPair&) = delete;

	cudaEvent_t start{};
	cudaEvent_t end{};
};

static cudaStream_t stream() {
	static cudaStream_t s = [] {
		cudaStream_t created;
		CUDA_CHECK(cudaStreamCreateWithFlags(&created, cudaStreamNonBlocking));
		return created;
	}();
	return s;
}

void synchronize() {
	CUDA_CHECK(cudaStreamSynchronize(stream()));
}

cudaStream_t computeStream() {
	return stream();
}

void* computeStreamHandle() {
	return stream();
}

Allocation::Allocation(size_t size): size(size) {
	if(size == 0)
		return;

	CUDA_CHECK(cudaHostAlloc(&host, size, cudaHostAllocMapped));
	CUDA_CHECK(cudaHostGetDevicePointer(&device, host, 0));
	memset(host, 0, size);
}

Allocation::~Allocation() {
	if(host != nullptr)
		cudaFreeHost(host);
}

static std::map<std::string, KernelEntry>& registry() {
	static std::map<std::string, KernelEntry> kernels;
	return kernels;
}

static std::string registryKey(const std::string& name, const std::string& variant) {
	return name + "|" + variant;
}

void registerKernel(KernelEntry entry) {
	std::string key = registryKey(entry.name, entry.variant);
	if(registry().contains(key)) {
		FATAL("[CUDA] Kernel " << entry.name << " (variant '" << entry.variant << "') registered twice");
	}
	registry().emplace(key, std::move(entry));
}

static std::string demangle(const std::type_index& type) {
	int status;
	char* name = abi::__cxa_demangle(type.name(), nullptr, nullptr, &status);
	std::string result = status == 0 ? name : type.name();
	free(name);
	return result;
}

static std::string signatureString(const std::vector<std::type_index>& signature) {
	std::stringstream ss;
	ss << "(";
	for(size_t i = 0; i < signature.size(); i++)
		ss << (i ? ", " : "") << demangle(signature[i]);
	ss << ")";
	return ss.str();
}

/** Maps OpenCL build options to a kernel variant: "-DRGGB" -> "RGGB", "" -> "". Multiple defines are joined by ','. */
static std::string variantFromOptions(const std::string& options) {
	std::stringstream in(options);
	std::string token;
	std::string variant;
	while(in >> token) {
		if(token.rfind("-D", 0) != 0) {
			FATAL("[CUDA] Unsupported kernel compile option: " << token);
		}
		variant += (variant.empty() ? "" : ",") + token.substr(2);
	}
	return variant;
}

} // namespace vpcuda


int cl::Event::wait() const {
	if(!pair)
		return CL_SUCCESS;

	cudaError_t error = cudaEventSynchronize(pair->end);
	return error == cudaSuccess ? CL_SUCCESS : (int)error;
}

float cl::Event::runtime() const {
	if(!pair)
		return 0.0f;

	CUDA_CHECK(cudaEventSynchronize(pair->end));
	float ms;
	CUDA_CHECK(cudaEventElapsedTime(&ms, pair->start, pair->end));
	return ms;
}

cl::Buffer::Buffer(size_t size, const void* data): alloc(std::make_shared<vpcuda::Allocation>(size)) {
	if(data != nullptr && size > 0)
		memcpy(alloc->host, data, size);
}

cl::Image2D::Image2D(int width, int height, int pixelBytes): width(width), height(height), pitch(width * pixelBytes), alloc(std::make_shared<vpcuda::Allocation>((size_t)width * pixelBytes * height)) {}


OpenCL::OpenCL() {
	int deviceCount = 0;
	cudaError_t error = cudaGetDeviceCount(&deviceCount);
	if(error != cudaSuccess || deviceCount == 0) {
		FATAL("No CUDA devices found (" << cudaGetErrorString(error) << "). Check CUDA installation!");
	}

	int device;
	CUDA_CHECK(cudaGetDevice(&device));
	cudaDeviceProp properties{};
	CUDA_CHECK(cudaGetDeviceProperties(&properties, device));
	if(!properties.canMapHostMemory) {
		FATAL("CUDA device " << properties.name << " can not map host memory (required for zero-copy buffers)");
	}

	LOG("Using device: CUDA " << CUDART_VERSION / 1000 << "." << (CUDART_VERSION % 1000) / 10 << " » " << properties.name << " (sm_" << properties.major << properties.minor << (properties.integrated ? ", integrated" : "") << ")");
	vpcuda::stream();
}

cl::Kernel OpenCL::compile(const char* code, const std::string& options) {
	auto kernel = std::find_if(std::begin(vpCudaKernelTable), std::end(vpCudaKernelTable), [&](const VpCudaKernelTableEntry& entry) { return entry.code == code; });
	if(kernel == std::end(vpCudaKernelTable)) {
		FATAL("[CUDA] Unknown kernel source passed to compile(), only the embedded kernel_*_cl sources are supported");
	}

	std::string variant = vpcuda::variantFromOptions(options);
	auto entry = vpcuda::registry().find(vpcuda::registryKey(kernel->name, variant));
	// Unported kernels only fail when they are run
	return {entry == vpcuda::registry().end() ? nullptr : &entry->second, kernel->name, variant};
}

cl::Event OpenCL::launch(const cl::Kernel& kernel, const cl::EnqueueArgs& args, const std::vector<std::type_index>& signature, vpcuda::GlobalSize& globalSize, void** params) {
	if(kernel.entry == nullptr) {
		if(kernel.name.empty()) {
			FATAL("[CUDA] Attempt to run an uncompiled kernel");
		}
		FATAL("[CUDA] Kernel " << kernel.name << " (variant '" << kernel.variant << "') is not ported to the CUDA backend yet");
	}

	const vpcuda::KernelEntry& entry = *kernel.entry;
	if(signature != entry.signature) {
		FATAL("[CUDA] Argument mismatch for kernel " << entry.name << " (variant '" << entry.variant << "'): called with " << vpcuda::signatureString(signature) << ", expected " << vpcuda::signatureString(entry.signature));
	}

	globalSize.x = (int)args.global.sizes[0];
	globalSize.y = (int)args.global.sizes[1];

	dim3 block = args.global.dimensions == 1 ? dim3(256, 1) : dim3(16, 16);
	dim3 grid((globalSize.x + block.x - 1) / block.x, (globalSize.y + block.y - 1) / block.y);

	std::shared_ptr<vpcuda::EventPair> pair = acquireEvent();
	CUDA_CHECK(cudaEventRecord(pair->start, vpcuda::stream()));
	if(globalSize.x > 0 && globalSize.y > 0) {
		cudaError_t error = cudaLaunchKernel(entry.function, grid, block, params, 0, vpcuda::stream());
		if(error != cudaSuccess) {
			FATAL("[CUDA] Enqueue kernel " << entry.name << " error: " << cudaGetErrorName(error) << " (" << cudaGetErrorString(error) << ")");
		}
	}
	CUDA_CHECK(cudaEventRecord(pair->end, vpcuda::stream()));
	return cl::Event(pair);
}

std::shared_ptr<vpcuda::EventPair> OpenCL::acquireEvent() {
	auto iterator = std::find_if(eventPool.begin(), eventPool.end(), [](const std::shared_ptr<vpcuda::EventPair>& e) { return e.use_count() == 1; });
	if(iterator != eventPool.end())
		return *iterator;

	auto pair = std::make_shared<vpcuda::EventPair>();
	eventPool.push_back(pair);
	return pair;
}

void OpenCL::wait(const cl::Event& event) {
	int error = event.wait();
	if(error != CL_SUCCESS) {
		FATAL("Error during kernel execution: " << cudaGetErrorName((cudaError_t)error) << " (" << cudaGetErrorString((cudaError_t)error) << ")");
	}
}

void OpenCL::printRuntimes() {
	std::cout << std::fixed;
	std::cout.precision(2);
	for(const cl::Event& event : events) {
		std::cout << event.runtime() << "ms ";
	}
	std::cout << std::endl;
}

void OpenCL::clearEvents() {
	events.clear();
}

//Pool design adapted from Jonathan Mee https://stackoverflow.com/a/27828584 CC BY-SA 3.0
std::shared_ptr<CLImage> OpenCL::acquire(const PixelFormat* format, int width, int height, const std::string& name) {
	std::vector<std::shared_ptr<CLImage>>& formatPool = pool[format];

	auto iterator = std::find_if(formatPool.begin(), formatPool.end(), [&](const std::shared_ptr<CLImage>& i){
		return i.use_count() == 1 && i->width == width && i->height == height;
	});
	if(iterator != formatPool.end()) {
		(*iterator)->name = name;
		return *iterator;
	}

	auto array = std::make_shared<CLImage>(format, width, height, name);
	formatPool.push_back(array);
	return array;
}

std::shared_ptr<RawImage> OpenCL::acquireNV12(int width, int height) {
	auto iterator = std::find_if(nv12pool.begin(), nv12pool.end(), [&](const std::shared_ptr<RawImage>& i){
		return i.use_count() == 1 && i->width == width && i->height == height;
	});
	if(iterator != nv12pool.end()) {
		return *iterator;
	}

	auto array = std::make_shared<RawImage>(&PixelFormat::NV12, width, height);
	nv12pool.push_back(array);
	return array;
}

CLArray::CLArray(int size): buffer((size_t)size), size(size) {}
CLArray::CLArray(void* data, const int size): buffer((size_t)size, data), size(size) {}

static inline cl::Image2D allocImage(int width, int height, const PixelFormat* format) {
	if(format->imageBytes == 0) {
		FATAL("Image creation error: pixel format can not be used as image " << width << "," << height);
	}
	return {width, height, format->imageBytes};
}

CLImage::CLImage(const PixelFormat* format): format(format), width(0), height(0) {}
CLImage::CLImage(const PixelFormat* format, int width, int height, std::string name): image(allocImage(width, height, format)), format(format), width(width), height(height), name(std::move(name)) {}

void CLImage::save(const std::string &suffix, float factor, float offset) const {
	if(format == &PixelFormat::F32) {
		cv::Mat grayscale(height, width, CV_8UC1);
		CLImageMap<float> map = read<float>();
		for(int y = 0; y < height; y++) {
			for(int x = 0; x < width; x++) {
				grayscale.data[x + width * y] = cv::saturate_cast<uint8_t>(factor * map(x, y) + offset);
			}
		}

		cv::imwrite("img/" + name + suffix, grayscale);
	} else if(format == &PixelFormat::RGBA8) {
		cv::Mat bgr;
		cv::cvtColor(read<RGBA>().cv, bgr, cv::COLOR_RGBA2BGR);
		cv::imwrite("img/" + name + suffix, bgr);
	} else {
		cv::imwrite("img/" + name + suffix, read<RGBA>().cv);
	}
}
