// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ssl_vision_wrapper.proto

#include "proto/ssl_vision_wrapper.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR SSL_WrapperPacket::SSL_WrapperPacket(
    ::_pbi::ConstantInitialized)
  : detection_(nullptr)
  , geometry_(nullptr)
  , config_(nullptr)
  , source_(0)
{}
struct SSL_WrapperPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SSL_WrapperPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SSL_WrapperPacketDefaultTypeInternal() {}
  union {
    SSL_WrapperPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SSL_WrapperPacketDefaultTypeInternal _SSL_WrapperPacket_default_instance_;
static ::_pb::Metadata file_level_metadata_proto_2fssl_5fvision_5fwrapper_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_proto_2fssl_5fvision_5fwrapper_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fssl_5fvision_5fwrapper_2eproto = nullptr;

const uint32_t TableStruct_proto_2fssl_5fvision_5fwrapper_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::SSL_WrapperPacket, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::SSL_WrapperPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::SSL_WrapperPacket, detection_),
  PROTOBUF_FIELD_OFFSET(::SSL_WrapperPacket, geometry_),
  PROTOBUF_FIELD_OFFSET(::SSL_WrapperPacket, source_),
  PROTOBUF_FIELD_OFFSET(::SSL_WrapperPacket, config_),
  0,
  1,
  3,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::SSL_WrapperPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_SSL_WrapperPacket_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fssl_5fvision_5fwrapper_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036proto/ssl_vision_wrapper.proto\032 proto/"
  "ssl_vision_detection.proto\032\037proto/ssl_vi"
  "sion_geometry.proto\032\031proto/ssl_vp_config"
  ".proto\"\234\001\n\021SSL_WrapperPacket\022&\n\tdetectio"
  "n\030\001 \001(\0132\023.SSL_DetectionFrame\022#\n\010geometry"
  "\030\002 \001(\0132\021.SSL_GeometryData\022\033\n\006source\030\003 \001("
  "\0162\013.SSL_Source\022\035\n\006config\030\004 \001(\0132\r.SSL_VPC"
  "onfig*\250\001\n\nSSL_Source\022\026\n\022SSL_SOURCE_UNKNO"
  "WN\020\000\022\024\n\020SSL_SOURCE_OTHER\020\001\022\031\n\025SSL_SOURCE"
  "_SSL_VISION\020\002\022\037\n\033SSL_SOURCE_VISION_PROCE"
  "SSOR\020\003\022\024\n\020SSL_SOURCE_GRSIM\020\004\022\032\n\026SSL_SOUR"
  "CE_ERFORCE_SIM\020\005"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto_deps[3] = {
  &::descriptor_table_proto_2fssl_5fvision_5fdetection_2eproto,
  &::descriptor_table_proto_2fssl_5fvision_5fgeometry_2eproto,
  &::descriptor_table_proto_2fssl_5fvp_5fconfig_2eproto,
};
static ::_pbi::once_flag descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto = {
    false, false, 456, descriptor_table_protodef_proto_2fssl_5fvision_5fwrapper_2eproto,
    "proto/ssl_vision_wrapper.proto",
    &descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto_once, descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_proto_2fssl_5fvision_5fwrapper_2eproto::offsets,
    file_level_metadata_proto_2fssl_5fvision_5fwrapper_2eproto, file_level_enum_descriptors_proto_2fssl_5fvision_5fwrapper_2eproto,
    file_level_service_descriptors_proto_2fssl_5fvision_5fwrapper_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto_getter() {
  return &descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fssl_5fvision_5fwrapper_2eproto(&descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SSL_Source_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto);
  return file_level_enum_descriptors_proto_2fssl_5fvision_5fwrapper_2eproto[0];
}
bool SSL_Source_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class SSL_WrapperPacket::_Internal {
 public:
  using HasBits = decltype(std::declval<SSL_WrapperPacket>()._has_bits_);
  static const ::SSL_DetectionFrame& detection(const SSL_WrapperPacket* msg);
  static void set_has_detection(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::SSL_GeometryData& geometry(const SSL_WrapperPacket* msg);
  static void set_has_geometry(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_source(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::SSL_VPConfig& config(const SSL_WrapperPacket* msg);
  static void set_has_config(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::SSL_DetectionFrame&
SSL_WrapperPacket::_Internal::detection(const SSL_WrapperPacket* msg) {
  return *msg->detection_;
}
const ::SSL_GeometryData&
SSL_WrapperPacket::_Internal::geometry(const SSL_WrapperPacket* msg) {
  return *msg->geometry_;
}
const ::SSL_VPConfig&
SSL_WrapperPacket::_Internal::config(const SSL_WrapperPacket* msg) {
  return *msg->config_;
}
void SSL_WrapperPacket::clear_detection() {
  if (detection_ != nullptr) detection_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void SSL_WrapperPacket::clear_geometry() {
  if (geometry_ != nullptr) geometry_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void SSL_WrapperPacket::clear_config() {
  if (config_ != nullptr) config_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
SSL_WrapperPacket::SSL_WrapperPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:SSL_WrapperPacket)
}
SSL_WrapperPacket::SSL_WrapperPacket(const SSL_WrapperPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_detection()) {
    detection_ = new ::SSL_DetectionFrame(*from.detection_);
  } else {
    detection_ = nullptr;
  }
  if (from._internal_has_geometry()) {
    geometry_ = new ::SSL_GeometryData(*from.geometry_);
  } else {
    geometry_ = nullptr;
  }
  if (from._internal_has_config()) {
    config_ = new ::SSL_VPConfig(*from.config_);
  } else {
    config_ = nullptr;
  }
  source_ = from.source_;
  // @@protoc_insertion_point(copy_constructor:SSL_WrapperPacket)
}

inline void SSL_WrapperPacket::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&detection_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&source_) -
    reinterpret_cast<char*>(&detection_)) + sizeof(source_));
}

SSL_WrapperPacket::~SSL_WrapperPacket() {
  // @@protoc_insertion_point(destructor:SSL_WrapperPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SSL_WrapperPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete detection_;
  if (this != internal_default_instance()) delete geometry_;
  if (this != internal_default_instance()) delete config_;
}

void SSL_WrapperPacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SSL_WrapperPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:SSL_WrapperPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(detection_ != nullptr);
      detection_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(geometry_ != nullptr);
      geometry_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(config_ != nullptr);
      config_->Clear();
    }
  }
  source_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SSL_WrapperPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .SSL_DetectionFrame detection = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_detection(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .SSL_GeometryData geometry = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_geometry(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .SSL_Source source = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::SSL_Source_IsValid(val))) {
            _internal_set_source(static_cast<::SSL_Source>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional .SSL_VPConfig config = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_config(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SSL_WrapperPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SSL_WrapperPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .SSL_DetectionFrame detection = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::detection(this),
        _Internal::detection(this).GetCachedSize(), target, stream);
  }

  // optional .SSL_GeometryData geometry = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::geometry(this),
        _Internal::geometry(this).GetCachedSize(), target, stream);
  }

  // optional .SSL_Source source = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_source(), target);
  }

  // optional .SSL_VPConfig config = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::config(this),
        _Internal::config(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SSL_WrapperPacket)
  return target;
}

size_t SSL_WrapperPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SSL_WrapperPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional .SSL_DetectionFrame detection = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *detection_);
    }

    // optional .SSL_GeometryData geometry = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *geometry_);
    }

    // optional .SSL_VPConfig config = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *config_);
    }

    // optional .SSL_Source source = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_source());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SSL_WrapperPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SSL_WrapperPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SSL_WrapperPacket::GetClassData() const { return &_class_data_; }

void SSL_WrapperPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SSL_WrapperPacket *>(to)->MergeFrom(
      static_cast<const SSL_WrapperPacket &>(from));
}


void SSL_WrapperPacket::MergeFrom(const SSL_WrapperPacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SSL_WrapperPacket)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_detection()->::SSL_DetectionFrame::MergeFrom(from._internal_detection());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_geometry()->::SSL_GeometryData::MergeFrom(from._internal_geometry());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_config()->::SSL_VPConfig::MergeFrom(from._internal_config());
    }
    if (cached_has_bits & 0x00000008u) {
      source_ = from.source_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SSL_WrapperPacket::CopyFrom(const SSL_WrapperPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SSL_WrapperPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSL_WrapperPacket::IsInitialized() const {
  if (_internal_has_detection()) {
    if (!detection_->IsInitialized()) return false;
  }
  if (_internal_has_geometry()) {
    if (!geometry_->IsInitialized()) return false;
  }
  if (_internal_has_config()) {
    if (!config_->IsInitialized()) return false;
  }
  return true;
}

void SSL_WrapperPacket::InternalSwap(SSL_WrapperPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SSL_WrapperPacket, source_)
      + sizeof(SSL_WrapperPacket::source_)
      - PROTOBUF_FIELD_OFFSET(SSL_WrapperPacket, detection_)>(
          reinterpret_cast<char*>(&detection_),
          reinterpret_cast<char*>(&other->detection_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SSL_WrapperPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto_getter, &descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto_once,
      file_level_metadata_proto_2fssl_5fvision_5fwrapper_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SSL_WrapperPacket*
Arena::CreateMaybeMessage< ::SSL_WrapperPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SSL_WrapperPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
