// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ssl_vision_wrapper.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fssl_5fvision_5fwrapper_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fssl_5fvision_5fwrapper_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/ssl_vision_detection.pb.h"
#include "proto/ssl_vision_geometry.pb.h"
#include "proto/ssl_vp_config.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fssl_5fvision_5fwrapper_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fssl_5fvision_5fwrapper_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fssl_5fvision_5fwrapper_2eproto;
class SSL_WrapperPacket;
struct SSL_WrapperPacketDefaultTypeInternal;
extern SSL_WrapperPacketDefaultTypeInternal _SSL_WrapperPacket_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SSL_WrapperPacket* Arena::CreateMaybeMessage<::SSL_WrapperPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum SSL_Source : int {
  SSL_SOURCE_UNKNOWN = 0,
  SSL_SOURCE_OTHER = 1,
  SSL_SOURCE_SSL_VISION = 2,
  SSL_SOURCE_VISION_PROCESSOR = 3,
  SSL_SOURCE_GRSIM = 4,
  SSL_SOURCE_ERFORCE_SIM = 5
};
bool SSL_Source_IsValid(int value);
constexpr SSL_Source SSL_Source_MIN = SSL_SOURCE_UNKNOWN;
constexpr SSL_Source SSL_Source_MAX = SSL_SOURCE_ERFORCE_SIM;
constexpr int SSL_Source_ARRAYSIZE = SSL_Source_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SSL_Source_descriptor();
template<typename T>
inline const std::string& SSL_Source_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SSL_Source>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SSL_Source_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SSL_Source_descriptor(), enum_t_value);
}
inline bool SSL_Source_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SSL_Source* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SSL_Source>(
    SSL_Source_descriptor(), name, value);
}
// ===================================================================

class SSL_WrapperPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SSL_WrapperPacket) */ {
 public:
  inline SSL_WrapperPacket() : SSL_WrapperPacket(nullptr) {}
  ~SSL_WrapperPacket() override;
  explicit PROTOBUF_CONSTEXPR SSL_WrapperPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SSL_WrapperPacket(const SSL_WrapperPacket& from);
  SSL_WrapperPacket(SSL_WrapperPacket&& from) noexcept
    : SSL_WrapperPacket() {
    *this = ::std::move(from);
  }

  inline SSL_WrapperPacket& operator=(const SSL_WrapperPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSL_WrapperPacket& operator=(SSL_WrapperPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SSL_WrapperPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const SSL_WrapperPacket* internal_default_instance() {
    return reinterpret_cast<const SSL_WrapperPacket*>(
               &_SSL_WrapperPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SSL_WrapperPacket& a, SSL_WrapperPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(SSL_WrapperPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSL_WrapperPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SSL_WrapperPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SSL_WrapperPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SSL_WrapperPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SSL_WrapperPacket& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSL_WrapperPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SSL_WrapperPacket";
  }
  protected:
  explicit SSL_WrapperPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDetectionFieldNumber = 1,
    kGeometryFieldNumber = 2,
    kConfigFieldNumber = 4,
    kSourceFieldNumber = 3,
  };
  // optional .SSL_DetectionFrame detection = 1;
  bool has_detection() const;
  private:
  bool _internal_has_detection() const;
  public:
  void clear_detection();
  const ::SSL_DetectionFrame& detection() const;
  PROTOBUF_NODISCARD ::SSL_DetectionFrame* release_detection();
  ::SSL_DetectionFrame* mutable_detection();
  void set_allocated_detection(::SSL_DetectionFrame* detection);
  private:
  const ::SSL_DetectionFrame& _internal_detection() const;
  ::SSL_DetectionFrame* _internal_mutable_detection();
  public:
  void unsafe_arena_set_allocated_detection(
      ::SSL_DetectionFrame* detection);
  ::SSL_DetectionFrame* unsafe_arena_release_detection();

  // optional .SSL_GeometryData geometry = 2;
  bool has_geometry() const;
  private:
  bool _internal_has_geometry() const;
  public:
  void clear_geometry();
  const ::SSL_GeometryData& geometry() const;
  PROTOBUF_NODISCARD ::SSL_GeometryData* release_geometry();
  ::SSL_GeometryData* mutable_geometry();
  void set_allocated_geometry(::SSL_GeometryData* geometry);
  private:
  const ::SSL_GeometryData& _internal_geometry() const;
  ::SSL_GeometryData* _internal_mutable_geometry();
  public:
  void unsafe_arena_set_allocated_geometry(
      ::SSL_GeometryData* geometry);
  ::SSL_GeometryData* unsafe_arena_release_geometry();

  // optional .SSL_VPConfig config = 4;
  bool has_config() const;
  private:
  bool _internal_has_config() const;
  public:
  void clear_config();
  const ::SSL_VPConfig& config() const;
  PROTOBUF_NODISCARD ::SSL_VPConfig* release_config();
  ::SSL_VPConfig* mutable_config();
  void set_allocated_config(::SSL_VPConfig* config);
  private:
  const ::SSL_VPConfig& _internal_config() const;
  ::SSL_VPConfig* _internal_mutable_config();
  public:
  void unsafe_arena_set_allocated_config(
      ::SSL_VPConfig* config);
  ::SSL_VPConfig* unsafe_arena_release_config();

  // optional .SSL_Source source = 3;
  bool has_source() const;
  private:
  bool _internal_has_source() const;
  public:
  void clear_source();
  ::SSL_Source source() const;
  void set_source(::SSL_Source value);
  private:
  ::SSL_Source _internal_source() const;
  void _internal_set_source(::SSL_Source value);
  public:

  // @@protoc_insertion_point(class_scope:SSL_WrapperPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::SSL_DetectionFrame* detection_;
  ::SSL_GeometryData* geometry_;
  ::SSL_VPConfig* config_;
  int source_;
  friend struct ::TableStruct_proto_2fssl_5fvision_5fwrapper_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SSL_WrapperPacket

// optional .SSL_DetectionFrame detection = 1;
inline bool SSL_WrapperPacket::_internal_has_detection() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || detection_ != nullptr);
  return value;
}
inline bool SSL_WrapperPacket::has_detection() const {
  return _internal_has_detection();
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::_internal_detection() const {
  const ::SSL_DetectionFrame* p = detection_;
  return p != nullptr ? *p : reinterpret_cast<const ::SSL_DetectionFrame&>(
      ::_SSL_DetectionFrame_default_instance_);
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::detection() const {
  // @@protoc_insertion_point(field_get:SSL_WrapperPacket.detection)
  return _internal_detection();
}
inline void SSL_WrapperPacket::unsafe_arena_set_allocated_detection(
    ::SSL_DetectionFrame* detection) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(detection_);
  }
  detection_ = detection;
  if (detection) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SSL_WrapperPacket.detection)
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::release_detection() {
  _has_bits_[0] &= ~0x00000001u;
  ::SSL_DetectionFrame* temp = detection_;
  detection_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::unsafe_arena_release_detection() {
  // @@protoc_insertion_point(field_release:SSL_WrapperPacket.detection)
  _has_bits_[0] &= ~0x00000001u;
  ::SSL_DetectionFrame* temp = detection_;
  detection_ = nullptr;
  return temp;
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::_internal_mutable_detection() {
  _has_bits_[0] |= 0x00000001u;
  if (detection_ == nullptr) {
    auto* p = CreateMaybeMessage<::SSL_DetectionFrame>(GetArenaForAllocation());
    detection_ = p;
  }
  return detection_;
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::mutable_detection() {
  ::SSL_DetectionFrame* _msg = _internal_mutable_detection();
  // @@protoc_insertion_point(field_mutable:SSL_WrapperPacket.detection)
  return _msg;
}
inline void SSL_WrapperPacket::set_allocated_detection(::SSL_DetectionFrame* detection) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(detection_);
  }
  if (detection) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(detection));
    if (message_arena != submessage_arena) {
      detection = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, detection, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  detection_ = detection;
  // @@protoc_insertion_point(field_set_allocated:SSL_WrapperPacket.detection)
}

// optional .SSL_GeometryData geometry = 2;
inline bool SSL_WrapperPacket::_internal_has_geometry() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || geometry_ != nullptr);
  return value;
}
inline bool SSL_WrapperPacket::has_geometry() const {
  return _internal_has_geometry();
}
inline const ::SSL_GeometryData& SSL_WrapperPacket::_internal_geometry() const {
  const ::SSL_GeometryData* p = geometry_;
  return p != nullptr ? *p : reinterpret_cast<const ::SSL_GeometryData&>(
      ::_SSL_GeometryData_default_instance_);
}
inline const ::SSL_GeometryData& SSL_WrapperPacket::geometry() const {
  // @@protoc_insertion_point(field_get:SSL_WrapperPacket.geometry)
  return _internal_geometry();
}
inline void SSL_WrapperPacket::unsafe_arena_set_allocated_geometry(
    ::SSL_GeometryData* geometry) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(geometry_);
  }
  geometry_ = geometry;
  if (geometry) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SSL_WrapperPacket.geometry)
}
inline ::SSL_GeometryData* SSL_WrapperPacket::release_geometry() {
  _has_bits_[0] &= ~0x00000002u;
  ::SSL_GeometryData* temp = geometry_;
  geometry_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::SSL_GeometryData* SSL_WrapperPacket::unsafe_arena_release_geometry() {
  // @@protoc_insertion_point(field_release:SSL_WrapperPacket.geometry)
  _has_bits_[0] &= ~0x00000002u;
  ::SSL_GeometryData* temp = geometry_;
  geometry_ = nullptr;
  return temp;
}
inline ::SSL_GeometryData* SSL_WrapperPacket::_internal_mutable_geometry() {
  _has_bits_[0] |= 0x00000002u;
  if (geometry_ == nullptr) {
    auto* p = CreateMaybeMessage<::SSL_GeometryData>(GetArenaForAllocation());
    geometry_ = p;
  }
  return geometry_;
}
inline ::SSL_GeometryData* SSL_WrapperPacket::mutable_geometry() {
  ::SSL_GeometryData* _msg = _internal_mutable_geometry();
  // @@protoc_insertion_point(field_mutable:SSL_WrapperPacket.geometry)
  return _msg;
}
inline void SSL_WrapperPacket::set_allocated_geometry(::SSL_GeometryData* geometry) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(geometry_);
  }
  if (geometry) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(geometry));
    if (message_arena != submessage_arena) {
      geometry = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, geometry, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  geometry_ = geometry;
  // @@protoc_insertion_point(field_set_allocated:SSL_WrapperPacket.geometry)
}

// optional .SSL_Source source = 3;
inline bool SSL_WrapperPacket::_internal_has_source() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool SSL_WrapperPacket::has_source() const {
  return _internal_has_source();
}
inline void SSL_WrapperPacket::clear_source() {
  source_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::SSL_Source SSL_WrapperPacket::_internal_source() const {
  return static_cast< ::SSL_Source >(source_);
}
inline ::SSL_Source SSL_WrapperPacket::source() const {
  // @@protoc_insertion_point(field_get:SSL_WrapperPacket.source)
  return _internal_source();
}
inline void SSL_WrapperPacket::_internal_set_source(::SSL_Source value) {
  assert(::SSL_Source_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  source_ = value;
}
inline void SSL_WrapperPacket::set_source(::SSL_Source value) {
  _internal_set_source(value);
  // @@protoc_insertion_point(field_set:SSL_WrapperPacket.source)
}

// optional .SSL_VPConfig config = 4;
inline bool SSL_WrapperPacket::_internal_has_config() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || config_ != nullptr);
  return value;
}
inline bool SSL_WrapperPacket::has_config() const {
  return _internal_has_config();
}
inline const ::SSL_VPConfig& SSL_WrapperPacket::_internal_config() const {
  const ::SSL_VPConfig* p = config_;
  return p != nullptr ? *p : reinterpret_cast<const ::SSL_VPConfig&>(
      ::_SSL_VPConfig_default_instance_);
}
inline const ::SSL_VPConfig& SSL_WrapperPacket::config() const {
  // @@protoc_insertion_point(field_get:SSL_WrapperPacket.config)
  return _internal_config();
}
inline void SSL_WrapperPacket::unsafe_arena_set_allocated_config(
    ::SSL_VPConfig* config) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(config_);
  }
  config_ = config;
  if (config) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SSL_WrapperPacket.config)
}
inline ::SSL_VPConfig* SSL_WrapperPacket::release_config() {
  _has_bits_[0] &= ~0x00000004u;
  ::SSL_VPConfig* temp = config_;
  config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::SSL_VPConfig* SSL_WrapperPacket::unsafe_arena_release_config() {
  // @@protoc_insertion_point(field_release:SSL_WrapperPacket.config)
  _has_bits_[0] &= ~0x00000004u;
  ::SSL_VPConfig* temp = config_;
  config_ = nullptr;
  return temp;
}
inline ::SSL_VPConfig* SSL_WrapperPacket::_internal_mutable_config() {
  _has_bits_[0] |= 0x00000004u;
  if (config_ == nullptr) {
    auto* p = CreateMaybeMessage<::SSL_VPConfig>(GetArenaForAllocation());
    config_ = p;
  }
  return config_;
}
inline ::SSL_VPConfig* SSL_WrapperPacket::mutable_config() {
  ::SSL_VPConfig* _msg = _internal_mutable_config();
  // @@protoc_insertion_point(field_mutable:SSL_WrapperPacket.config)
  return _msg;
}
inline void SSL_WrapperPacket::set_allocated_config(::SSL_VPConfig* config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(config_);
  }
  if (config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(config));
    if (message_arena != submessage_arena) {
      config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  config_ = config;
  // @@protoc_insertion_point(field_set_allocated:SSL_WrapperPacket.config)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::SSL_Source> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SSL_Source>() {
  return ::SSL_Source_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fssl_5fvision_5fwrapper_2eproto
