#    Copyright 2024 Felix Weinmann
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

import argparse
import importlib
import os
import pathlib
import sys
import socket
import struct
import threading

from google.protobuf.json_format import MessageToDict

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_PYTHON_DIR = _REPO_ROOT / 'python'
_PROTO_OUT = _PYTHON_DIR / 'proto'


def _protos_importable():
    """True if the generated bindings load against *this* protobuf runtime.

    Existence is not enough: bindings generated by a protoc whose major
    version differs from the installed protobuf runtime import-fail rather
    than silently misbehave, so probe by importing.
    """
    if not (_PROTO_OUT / 'ssl_vision_wrapper_pb2.py').exists():
        return False
    try:
        importlib.import_module('proto.ssl_vision_wrapper_pb2')
        return True
    except Exception:
        # Drop the half-initialised modules so a later import retries cleanly.
        for name in [n for n in sys.modules if n.startswith('proto.')]:
            del sys.modules[name]
        return False


def _compile_protos():
    """Regenerate proto/*.proto into python/proto.

    Prefers grpc_tools.protoc from the running interpreter, because it ships
    with a generator matched to that interpreter's protobuf runtime. A bare
    `protoc` off $PATH is a common source of gencode/runtime mismatches: on
    Ubuntu 20.04 it is 3.6.1 while pip's protobuf is 5.x, and 5.x refuses
    pre-3.19 gencode.
    """
    print("Compiling Protobuf files...")
    sources = sorted(_REPO_ROOT.glob('proto/*.proto'))
    if not sources:
        raise RuntimeError(f'no .proto files found in {_REPO_ROOT / "proto"}')
    args = [str(path.relative_to(_REPO_ROOT)) for path in sources]
    _PROTO_OUT.mkdir(parents=True, exist_ok=True)

    try:
        from grpc_tools import protoc as grpc_protoc
        if grpc_protoc.main(['protoc', f'-I{_REPO_ROOT}',
                             f'--python_out={_PYTHON_DIR}', *args]) == 0:
            return
    except ImportError:
        pass

    import subprocess
    base = ['protoc', f'-I{_REPO_ROOT}', f'--python_out={_PYTHON_DIR}']
    try:
        # --pyi_out needs a newer protoc than Ubuntu 20.04/22.04 ships. This is
        # a probe, so keep its failure output off the console.
        subprocess.run([*base, f'--pyi_out={_PYTHON_DIR}', *args], check=True,
                       stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        subprocess.run([*base, *args], check=True)


if not _protos_importable():
    _compile_protos()
    if not _protos_importable():
        import google.protobuf
        raise SystemExit(
            f'Generated protobuf bindings in {_PROTO_OUT} are not loadable by '
            f'this interpreter (protobuf runtime {google.protobuf.__version__}).\n'
            'No compatible generator was found: grpc_tools is not installed '
            'here, and the protoc on PATH is too old to match the runtime.\n'
            'Fix by either running this script with the project venv '
            '(.venv/bin/python), or installing a matching generator:\n'
            '    pip install --user grpcio-tools'
        )


from proto.ssl_vision_wrapper_pb2 import SSL_WrapperPacket


def parser_vision_network(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    parser.add_argument('--vision_ip', default='224.5.23.2', help='Multicast IP address of the vision')
    parser.add_argument('--vision_port', type=int, default=10006, help='Multicast port of the vision')
    return parser


def open_multicast_socket(ip, port):
    # Adapted from https://stackoverflow.com/a/1794373 (CC BY-SA 4.0 by Gordon Wrigley)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)

    TTL = 32
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, struct.pack('b', TTL))
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
    sock.bind((ip, port))
    try:
        sock.setsockopt(
            socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP,
            struct.pack("4sl", socket.inet_aton(ip), socket.INADDR_ANY)
        )
    except:
        print("Could not join multicast group")
    return sock


class VisionSocket:

    def __init__(self, vision_ip='224.5.23.2', vision_port=10006, args: argparse.Namespace=None):
        if args:
            vision_ip = args.vision_ip
            vision_port = args.vision_port

        self.running = False
        self.address = (vision_ip, vision_port)
        self.socket = open_multicast_socket(vision_ip, vision_port)

    def consume(self, wrapper: SSL_WrapperPacket):
        pass

    def send(self, wrapper: SSL_WrapperPacket):
        self.socket.sendto(wrapper.SerializeToString(), self.address)

    def _receive_thread(self):
        while self.running:
            data = self.socket.recv(65536)
            if not self.running and len(data) == 0:
                return

            wrapper = SSL_WrapperPacket()
            wrapper.ParseFromString(data)
            self.consume(wrapper)

    def __enter__(self):
        self.running = True
        self.thread = threading.Thread(target=self._receive_thread, name="Vision receiver")
        self.thread.start()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.running = False
        self.socket.sendto(b'', self.address)
        self.thread.join()


class VisionRecorder(VisionSocket):

    def __init__(self, vision_ip='224.5.23.2', vision_port=10006, args: argparse.Namespace=None):
        self.packets = []
        super().__init__(vision_ip, vision_port, args)

    def subfield(self, field: str) -> list:
        return [getattr(packet, field) for packet in self.packets if packet.HasField(field)]

    def dict_subfield(self, field: str) -> list[dict]:
        return [MessageToDict(packet, preserving_proto_field_name=True) for packet in self.subfield(field)]

    def __enter__(self):
        self.packets.clear()
        return super().__enter__()

    def consume(self, wrapper: SSL_WrapperPacket):
        self.packets.append(wrapper)
